<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>hello_book</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="2.3.0" />
    <PackageReference Include="Microsoft.Configuration.CommandLine" Version="2.3.0" />
    <PackageReference Include="MediatR" Version="9.0.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="9.0.0" />
  </ItemGroup>
</Project>