using MediatR;
// ...existing code...

public void ConfigureServices(IServiceCollection services)
{
    // ...existing code...
    services.AddMediatR(typeof(Startup));
    // ...existing code...
}

// ...existing code...
